### ISSUE TITLE
Loyal pet has extra bonus

### ISSUE THREAD

**Issue by AnnieRuru** [HerculesWS/Hercules#2435]
**Is your feature request related to a problem? Please describe.**
https://rathena.org/board/topic/105838-renewal-pet-bonus-implementation/?tab=comments#comment-359384

**Describe the solution you'd like**
[rathena pet_db.yml](https://github.com/rathena/rathena/blob/master/db/re/pet_db.yml)
```yml
  - Mob: PORING
    TameItem: Unripe_Apple
    EggItem: Poring_Egg
    EquipItem: Backpack
    FoodItem: Apple_Juice
    Fullness: 3
    IntimacyFed: 50
    CaptureRate: 2000
    Script: >
      .@i = getpetinfo(PETINFO_INTIMATE);
      
      if( .@i >= PET_INTIMATE_LOYAL ){
        bonus bLuk,2;
        bonus bCritical,1;
      }
    Evolution:
      - Target: MASTERING
        ItemRequirements:
          - Item: Leaf_Of_Yggdrasil
            Amount: 10
          - Item: Unripe_Apple
            Amount: 3
```

**Describe alternatives you've considered**
not really sure about just adding 
```
	EquipScript: <"
		bonus(bLuk, 2);
		bonus(bCritical, 1);
		if ( getpetinfo(PETINFO_INTIMACY) >= PET_INTIMATE_LOYAL )
			bonus(bLuk, 1);
	">
```
maybe something like ... ?
```
	EquipScript: <"
		.@intimacy = getpetinfo(PETINFO_INTIMACY);
		if ( .@intimacy >= PET_INTIMATE_LOYAL ) {
			bonus(bLuk, 3);
			bonus(bCritical, 1);
		} else if ( .@intimacy >= PET_INTIMATE_CORDIAL ) {
			bonus(bLuk, 2);
			bonus(bCritical, 1);
		}
	">
```

**Additional context**
I think this is official, otherwise rathena wont do it
```lua
	[9001] = {
		unidentifiedDisplayName = "Poring Egg",
		unidentifiedResourceName = "수속성알",
		unidentifiedDescriptionName = {
		},
		identifiedDisplayName = "Poring Egg",
		identifiedResourceName = "수속성알",
		identifiedDescriptionName = {
			"An egg in which a Poring Cute Pet rests.",
			"Can be hatched by using a ^6666CCPet Incubator^000000.",
			"If pet intimacy is Cordial, LUK +2, CRIT +1.",
			"If pet intimacy is Loyal, LUK +3, CRIT +1.",
			"^ffffff_^000000",
			"Class:^6666CC Monster Egg^000000"
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false
	},
```
